ClientManager/Models/picture.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class picture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public picture()
        {
            this.comments = new HashSet<comment>();
            this.likes = new HashSet<like>();
            this.persons = new HashSet<person>();
        }
    
        public int picture_id { get; set; }
        public int person_id { get; set; }
        public string caption { get; set; }
        public string relative_path { get; set; }
        public string time_info { get; set; }
        public string location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<like> likes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<person> persons { get; set; }
        public virtual person person { get; set; }
    }
}

ClientManager/Controllers/CommentController.cs
using ClientManager.ActionFilters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientManager.Controllers
{
    public class CommentController : Controller
    {
        Models.ClientsEntities db = new Models.ClientsEntities(); 

        // GET: Comment
        public ActionResult Index(int id) //picture_id
        {
            Models.picture pictureComments = db.pictures.SingleOrDefault(p => p.picture_id == id);

            return View(pictureComments);
        }

        // GET: Comment/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Comment/Create
        [HttpPost]
        public ActionResult Create(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                int userId = int.Parse(Session["user_id"].ToString());
                Models.user theCommenter = db.users.SingleOrDefault(u => u.user_id == userId);

                Models.comment newComment = new Models.comment()
                {
                    picture_id = id,
                    comment1 = collection["comment1"],
                    person_id = (int)theCommenter.person_id,
                    timestamp = DateTime.Now.ToString(),
                };
                db.comments.Add(newComment);
                db.SaveChanges();

                return RedirectToAction("Index", new { id = id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Comment/Edit/5
        public ActionResult Edit(int id)
        {
            Models.comment theComment = db.comments.SingleOrDefault(c => c.comment_id == id);
            return View(theComment);
        }

        // POST: Comment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                int UserId = int.Parse(Session["user_id"].ToString());
                Models.comment theComment = db.comments.SingleOrDefault(c => c.comment_id == id);

                // TODO: Add update logic 
                theComment.comment1 = collection["comment1"];
                theComment.timestamp = DateTime.Now.ToString();

                db.SaveChanges();

                return RedirectToAction("Index", new { id = theComment.picture_id});
            }
            catch
            {
                return View();
            }
        }

        // GET: Comment/Delete/5
        public ActionResult Delete(int id)
        {
            Models.comment theComment = db.comments.SingleOrDefault(c => c.comment_id == id);

            return View(theComment);
        }

        // POST: Comment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Models.comment theComment = db.comments.SingleOrDefault(c => c.comment_id == id);
                db.comments.Remove(theComment);
                db.SaveChanges();

                return RedirectToAction("Index", new { id = theComment.picture_id});
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Like(int id)
        {
            try
            {
                // TODO: Add delete logic here
                int userId = int.Parse(Session["user_id"].ToString());
                int personId = (int)db.users.SingleOrDefault(u => u.user_id == userId).person_id;
                Models.comment theLikedComment = db.comments.SingleOrDefault(p => p.comment_id == id);

                Models.comment_like likedComment = new Models.comment_like
                {
                    comment_id = id,
                    person_id = personId,

                    timestamp = DateTime.Now.ToString(),
                };

                db.comment_like.Add(likedComment);
                db.SaveChanges();

                return RedirectToAction("Index", new { id = theLikedComment.picture_id});
            }
            catch
            {
                db.SaveChanges();
                return View();
            }
        }

        public ActionResult UnLike(int id)
        {
            try
            {
                // TODO: Add delete logic here
                int userId = int.Parse(Session["user_id"].ToString());
                int personId = (int)db.users.SingleOrDefault(u => u.user_id == userId).person_id;
                Models.comment theLikedComment = db.comments.SingleOrDefault(p => p.comment_id == id);

                Models.comment_like likedComment = db.comment_like.SingleOrDefault(p => p.comment_id == id);

                db.comment_like.Remove(likedComment);
                db.SaveChanges();

                return RedirectToAction("Index", new { id = theLikedComment.picture_id });
            }
            catch
            {
                db.SaveChanges();
                return View();
            }
        }
    }
}

ClientManager/Controllers/PictureController.cs
using ClientManager.ActionFilters;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientManager.Controllers
{
  
    public class PictureController : Controller
    {
        Models.ClientsEntities db = new Models.ClientsEntities();

        // GET: Picture
        public ActionResult Index(int id)
        {
            Models.person thePerson = db.persons.SingleOrDefault(p => p.person_id == id);

            return View(thePerson);
        }

        public ActionResult ChooseProfilePic(int picture_id, int person_id) // person_id
        {
            try
            {
                Models.person thePerson = db.persons.SingleOrDefault(p => p.person_id == person_id);
                Models.picture thePicture = db.pictures.SingleOrDefault(p => p.picture_id == picture_id);

                thePerson.profile_pic = thePicture.picture_id;
                
                db.SaveChanges();

                return View("Index", thePerson);
            }
            catch
            {
                return View();
            }
        }

        // GET: Picture/Details/5
        public ActionResult Details(int id)
        {
            Models.picture thePic = db.pictures.SingleOrDefault(p => p.picture_id == id);

            return View(thePic);
        }

        [PictureFilter]
        // GET: Picture/Create
        public ActionResult Create(int id)
        {
            ViewBag.person = db.persons.SingleOrDefault(p => p.person_id == id);

            return View();
        }

        // POST: Picture/Create
        [PictureFilter]
        [HttpPost]
        public ActionResult Create(int id,FormCollection collection, HttpPostedFileBase newPicture)
        {
            try
            {
                // TODO: Add insert logic here
                // type checking
                string[] types = { "image/gif", "image/jpeg", "image/png" };

                if(newPicture != null 
                    && newPicture.ContentLength > 0 
                    && types.Contains(newPicture.ContentType))
                {
                    Guid g = Guid.NewGuid();
                    string filename = g + "." + Path.GetExtension(newPicture.FileName);
                    string path = Server.MapPath("~/Images/");
                    path = Path.Combine(path, filename);
                    newPicture.SaveAs(path);

                    Models.picture newPic = new Models.picture()
                    {
                        caption = collection["caption"],
                        time_info = collection["time_info"],
                        location = collection["location"],
                        relative_path = filename,
                        person_id = id,
                    };

                    db.pictures.Add(newPic);
                    db.SaveChanges();
                }

                return RedirectToAction("Index", new { id = id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Picture/Edit/5
        public ActionResult Edit(int id)
        {
            Models.picture thePic = db.pictures.SingleOrDefault(p => p.picture_id == id);

            return View(thePic);
        }

        // POST: Picture/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection, HttpPostedFileBase newPicture) // picture_id
        {
            try
            {
                // TODO: Add update logic here
                string[] types = { "image/gif", "image/jpeg", "image/png" };
                Models.picture thePic = db.pictures.SingleOrDefault(p => p.picture_id == id);

                if (newPicture != null
                   && newPicture.ContentLength > 0
                   && types.Contains(newPicture.ContentType))
                {
                    Guid g = Guid.NewGuid();
                    string filename = g + "." + Path.GetExtension(newPicture.FileName);
                    string path = Server.MapPath("~/Images/");
                    path = Path.Combine(path, filename);
                    newPicture.SaveAs(path);

                    thePic.caption = collection["caption"];
                    thePic.time_info = collection["time_info"];
                    thePic.location = collection["location"];
                    thePic.relative_path = filename;

                    db.SaveChanges();
                }

                return RedirectToAction("Index", new { id = thePic.person_id });
            }
            catch
            {
                return View();
            }
        }

        // GET: Picture/Delete/5
        public ActionResult Delete(int id)
        {
            Models.picture thePic = db.pictures.SingleOrDefault(p => p.picture_id == id);

            return View(thePic);
        }

        // POST: Picture/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                Models.picture thePic = db.pictures.SingleOrDefault(p => p.picture_id == id);
                db.pictures.Remove(thePic);
                db.SaveChanges();

                return RedirectToAction("Index", new { id = thePic.person_id});
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Like(int id)
        {
            try
            {
                // TODO: Add delete logic here
                int userId = int.Parse(Session["user_id"].ToString());
                int personId = (int) db.users.SingleOrDefault(u => u.user_id == userId).person_id;
                Models.picture theLikedPicture = db.pictures.SingleOrDefault(p => p.picture_id == id);

                Models.like likedPicture = new Models.like
                {
                    picture_id = id,
                    person_id = personId,

                    timestamp = DateTime.Now.ToString(),
                };

                db.likes.Add(likedPicture);
                db.SaveChanges();

                return RedirectToAction("Index", new { id = theLikedPicture.person_id });
            }
            catch
            {
                db.SaveChanges();
                return View();
            }
        }

        public ActionResult UnLike(int id)
        {
            try
            {
                // TODO: Add delete logic here
                int userId = int.Parse(Session["user_id"].ToString());
                int personId = (int)db.users.SingleOrDefault(u => u.user_id == userId).person_id;
                Models.picture theLikedPicture = db.pictures.SingleOrDefault(p => p.picture_id == id);

                Models.like likedPicture = db.likes.SingleOrDefault(p => p.picture_id == id && p.person_id == personId);

                db.likes.Remove(likedPicture);
                db.SaveChanges();

                return RedirectToAction("Index", new { id = theLikedPicture.person_id});
            }
            catch
            {
                db.SaveChanges();
                return View();
            }
        }
    }
}

ClientManager/Views/Picture/Create.cshtml
@model ClientManager.Models.picture

@{
    ViewBag.Title = "Create";
    ClientManager.Models.person aPerson = ViewBag.person;
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Picture", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>picture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.caption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.EditorFor(model => model.caption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.caption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.relative_path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="newPicture" class="form-control text-box single-line"/>
                @*@Html.EditorFor(model => model.relative_path, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.relative_path, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time_info, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time_info, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.time_info, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = aPerson.person_id}, null)
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ClientManager/Views/Picture/Delete.cshtml
@model ClientManager.Models.picture

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>picture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.caption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.caption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.relative_path)
        </dt>

        <dd>
            <img src="/Images/@Html.DisplayFor(model => model.relative_path)" style="max-height:100px; max-width:100px" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time_info)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time_info)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.person.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.person.first_name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { id = Model.picture_id})
        </div>
    }
</div>

ClientManager/Views/Picture/Details.cshtml
@model ClientManager.Models.picture

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>picture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.caption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.caption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.relative_path)
        </dt>

        <dd>
            <img src="/Images/@Html.DisplayFor(model => model.relative_path)" style="max-height:100px; max-width:100px" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time_info)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time_info)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.person.first_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.person.first_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.picture_id }) |
    @Html.ActionLink("Back to List", "Index", new { id = Model.person_id })
</p>

ClientManager/Views/Picture/Edit.cshtml
@model ClientManager.Models.picture

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("edit", "Picture", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>picture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.picture_id)

        @*<div class="form-group">
            @Html.LabelFor(model => model.person_id, "person_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("person_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.person_id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.caption, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.caption, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.caption, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.relative_path, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="newPicture" class="form-control text-box single-line" />
                @*@Html.EditorFor(model => model.relative_path, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.relative_path, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.time_info, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.time_info, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.time_info, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = Model.person_id})
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ClientManager/Views/Picture/Index.cshtml
@model ClientManager.Models.person

@{
    ViewBag.Title = "Index";
    ClientManager.Models.ClientsEntities db = new ClientManager.Models.ClientsEntities();
    int userId = int.Parse(Session["user_id"].ToString());
    int personId = (int)db.users.SingleOrDefault(p => p.user_id == userId).person_id;

    var checkProfile = db.persons.SingleOrDefault(p => p.person_id == personId) != null ? true : false;
}

<h2>
    @Html.DisplayFor(model => model.first_name)
    @Html.DisplayFor(model => model.last_name)
</h2>

<p>
    @Html.ActionLink("Create New", "Create", new { id = Model.person_id })
</p>

<p>
    Profile picture:
    <img src="/Images/@Html.DisplayFor(modelItem => modelItem.picture.relative_path)" style="max-height:100px; max-width:100px" />
</p>

@Html.Partial("PictureAlbum", Model.pictures)
@Html.ActionLink("Back to Profile", "index", "Profile")

ClientManager/Views/Picture/PictureAlbum.cshtml
@model IEnumerable<ClientManager.Models.picture>

@{ 
    ClientManager.Models.ClientsEntities db = new ClientManager.Models.ClientsEntities();
    int userId = int.Parse(Session["user_id"].ToString());
    int personId = (int) db.users.SingleOrDefault(p => p.user_id == userId).person_id;
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.caption)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.relative_path)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.time_info)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.location)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {

    bool checkLike = db.likes.SingleOrDefault(p => p.person_id == personId && p.picture_id == item.picture_id) != null ? true : false;

    ClientManager.Models.picture checkProfile = db.pictures.SingleOrDefault(p => p.person_id == personId
        && p.picture_id == item.picture_id);
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.caption)
        </td>
        <td>
            <img src="/Images/@Html.DisplayFor(modelItem => item.relative_path)" style="max-height:100px; max-width:100px" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.time_info)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.location)
        </td>
        <td>
            @if (checkLike)
            {
                @Html.ActionLink("UnLike", "UnLike", new { id = item.picture_id })
            }
            else
            {
                @Html.ActionLink("Like", "like", new { id = item.picture_id })
            }
        </td>
        <td>
            @Html.ActionLink("View Comments", "Index", "Comment", new { id = item.picture_id }, null)

            @if (checkProfile != null &&
                (checkProfile.person_id == item.person_id && checkProfile.picture_id == item.picture_id))
            {
                @Html.ActionLink("| Select as Profile Picture", "ChooseProfilePic", new { picture_id = item.picture_id, person_id = item.person_id }, null) 
                @Html.ActionLink(" | Edit", "Edit", new { id = item.picture_id }) 
                @Html.ActionLink(" | Details", "Details", new { id = item.picture_id }) 
                @Html.ActionLink(" | Delete", "Delete", new { id = item.picture_id })
            }
        </td>
    </tr>
}

</table>